version: '3'

services:

  grafana:
    image: grafana/grafana
    container_name: oau-netology-grafana
    environment:
      GF_PATHS_CONFIG: /etc/grafana/custom.ini
    ports:
      - 80:3000
    volumes:
      - ./grafana:/etc/grafana
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring-stack
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  grafana-data:
