version: '3'

services:

  pushgateway:
    image: prom/pushgateway:v1.6.2
    container_name: oau-netology-pushgateway
    ports:
      - 9091:9091
    networks:
      - monitoring-stack
    depends_on:
      - prometheus
    restart: unless-stopped
