```
version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: oau-netology-prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    networks:
      - monitoring-stack
    restart: always
    
  pushgateway:
    image: prom/pushgateway:v1.6.2
    container_name: oau-netology-pushgateway
    ports:
      - 9091:9091
    networks:
      - monitoring-stack
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus-data:

networks:
  monitoring-stack:
    name: oau-netology-hw
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
```
